# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui,QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_SendMailer(object):
    def setupUi(self, SendMailer):
        SendMailer.setObjectName(repr("SendMailer"))
        SendMailer.resize(600, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(SendMailer)
        self.verticalLayout.setObjectName(repr("verticalLayout"))
        self.groupBox = QtWidgets.QGroupBox(SendMailer)
        # self.groupBox.setMinimumSize(QtCore.QSize(0, 90))
        # self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setObjectName(repr("groupBox"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(repr("verticalLayout_4"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(repr("horizontalLayout_7"))
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName(repr("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.comboBoxServer = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxServer.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxServer.setObjectName(repr("comboBoxServer"))
        self.horizontalLayout_7.addWidget(self.comboBoxServer)
        self.lineEditSMTP = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditSMTP.setObjectName(repr("lineEditSMTP"))
        self.horizontalLayout_7.addWidget(self.lineEditSMTP)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName(repr("line_4"))
        self.verticalLayout_4.addWidget(self.line_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(repr("horizontalLayout_8"))
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName(repr("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lineEditUser = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditUser.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditUser.setObjectName(repr("lineEditUser"))
        self.horizontalLayout_8.addWidget(self.lineEditUser)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName(repr("line_5"))
        self.horizontalLayout_8.addWidget(self.line_5)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName(repr("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.lineEditPasswd = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditPasswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPasswd.setObjectName(repr("lineEditPasswd"))
        self.horizontalLayout_8.addWidget(self.lineEditPasswd)
        self.checkBoxRememberUP = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxRememberUP.setObjectName(repr("checkBoxRememberUP"))
        self.horizontalLayout_8.addWidget(self.checkBoxRememberUP)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(SendMailer)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 90))
        self.groupBox_2.setObjectName(repr("groupBox_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(repr("verticalLayout_2"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(repr("horizontalLayout_2"))
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName(repr("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEditReceiver = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditReceiver.setObjectName(repr("lineEditReceiver"))
        self.horizontalLayout_2.addWidget(self.lineEditReceiver)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName(repr("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(repr("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(repr("horizontalLayout_3"))
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName(repr("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.lineEditCheme = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditCheme.setObjectName(repr("lineEditCheme"))
        self.horizontalLayout_3.addWidget(self.lineEditCheme)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName(repr("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(repr("verticalLayout_3"))
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName(repr("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.textEditBody = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEditBody.setObjectName(repr("textEditBody"))
        self.verticalLayout_3.addWidget(self.textEditBody)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(repr("horizontalLayout_4"))
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName(repr("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.attachBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.attachBtn.setObjectName(repr("attachBtn"))
        self.horizontalLayout_4.addWidget(self.attachBtn)
        self.lineEditAttach = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditAttach.setObjectName(repr("lineEditAttach"))
        self.horizontalLayout_4.addWidget(self.lineEditAttach)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(repr("horizontalLayout_6"))
        self.progressBarSend = QtWidgets.QProgressBar(SendMailer)
        self.progressBarSend.setProperty("value", 24)
        self.progressBarSend.setObjectName(repr("progressBarSend"))
        self.horizontalLayout_6.addWidget(self.progressBarSend)
        self.labelSendMsg = QtWidgets.QLabel(SendMailer)
        self.labelSendMsg.setMinimumSize(QtCore.QSize(71, 90))
        self.labelSendMsg.setObjectName(repr("labelSendMsg"))
        self.horizontalLayout_6.addWidget(self.labelSendMsg)
        spacerItem = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.sendingBtn = QtWidgets.QPushButton(SendMailer)
        self.sendingBtn.setObjectName(repr("sendingBtn"))
        self.horizontalLayout_6.addWidget(self.sendingBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(SendMailer)
        QtCore.QMetaObject.connectSlotsByName(SendMailer)

    def retranslateUi(self, SendMailer):
        SendMailer.setWindowTitle(_translate("SendMailer", "Form", None))
        self.groupBox.setTitle(_translate("SendMailer", "配置项", None))
        self.label.setText(_translate("SendMailer", "服务器地址：", None))
        self.lineEditSMTP.setText(_translate("SendMailer", "自定义", None))
        self.label_2.setText(_translate("SendMailer", "用户名：", None))
        self.label_3.setText(_translate("SendMailer", "密码：", None))
        self.checkBoxRememberUP.setText(_translate("SendMailer", "记住用户名密码", None))
        self.groupBox_2.setTitle(_translate("SendMailer", "内容项", None))
        self.label_5.setText(_translate("SendMailer", "接收人：  ", None))
        self.label_6.setText(_translate("SendMailer", "多个用, 分隔开", None))
        self.label_7.setText(_translate("SendMailer", "邮件主题：", None))
        self.label_8.setText(_translate("SendMailer", "邮件正文：", None))
        self.label_4.setText(_translate("SendMailer", "邮件附件：", None))
        self.attachBtn.setText(_translate("SendMailer", "选择附件", None))
        self.labelSendMsg.setText(_translate("SendMailer", "    发送消息", None))
        self.sendingBtn.setText(_translate("SendMailer", "开始发送", None))


# if __name__ == "__main__":
#     import sys
#     app = QtGui.QGuiApplication(sys.argv)
#     # SendMailer = QtGui.QWidget()
#     ui = Ui_SendMailer()
#     ui.setupUi(SendMailer)
#     SendMailer.show()
#     sys.exit(app.exec_())